In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/LJL/Downloads/sec_files.txt", header=None)
data = data[0].str.split(expand=True)
data.columns = ["date", "time", "index", "file"]
data

              date      time   index       file
0       2021-11-16  11:36:28    3354      0.txt
1       2021-11-16  11:36:29    3356      1.txt
2       2021-11-16  11:36:33   34433     10.txt
3       2021-11-16  11:37:19    6699    100.txt
4       2021-11-16  11:46:42  419763   1000.txt
...            ...       ...     ...        ...
413304  2021-11-17  08:51:33   96033  99995.txt
413305  2021-11-17  08:51:33    6632  99996.txt
413306  2021-11-17  08:51:34    7018  99997.txt
413307  2021-11-17  08:51:35    9281  99998.txt
413308  2021-11-17  08:51:35    4402  99999.txt

[413309 rows x 4 columns]

In [3]:
training_mapping = pd.read_csv("mapping_with_label_training.csv", index_col=0)
training_mapping

,file_number,date,ticker,cik,form_type,url,label
0,0,2015-01-09,AEE,1002910,4,http://www.sec.gov/Archives/edgar/data/1002910...,1.0
1,1,2015-01-09,AEE,1002910,4,http://www.sec.gov/Archives/edgar/data/1002910...,1.0
2,2,2015-01-09,AEE,1002910,4,http://www.sec.gov/Archives/edgar/data/1002910...,1.0
3,3,2015-01-09,AEE,1002910,4,http://www.sec.gov/Archives/edgar/data/1002910...,1.0
4,4,2015-01-09,AEE,1002910,4,http://www.sec.gov/Archives/edgar/data/1002910...,1.0
...,...,...,...,...,...,...,...
401478,520412,2019-12-17,RJF,720005,4,http://www.sec.gov/Archives/edgar/data/720005/...,-1.0
401479,520413,2019-12-17,RJF,720005,4,http://www.sec.gov/Archives/edgar/data/720005/...,-1.0
401480,520414,2019-12-17,RJF,720005,4,http://www.sec.gov/Archives/edgar/data/720005/...,-1.0
401481,520415,2019-12-17,RJF,720005,4,http://www.sec.gov/Archives/edgar/data/720005/...,-1.0
401482,520416,2019-12-17,RJF,720005,4,http://www.sec.gov/Archives/edgar/data/720005/...,-1.0

In [4]:
needed = list(set(list(training_mapping["file_number"])))
have = set(list(data["file"]))
need_upload = []
for file in needed:
    if str(file) + ".txt" not in have:
        need_upload.append(file)
need_upload

[]

In [5]:
len(need_upload)

0

In [6]:
print(need_upload[0])
need_upload[-1]

IndexError: list index out of range