In [2]:
import pandas as pd
import numpy as np

In [6]:
import yfinance as yf
import pandas as pd
single_df = yf.download("SPY", 
                      start='2014-01-01', 
                      end='2021-10-08', 
                      progress=False)
single_df = single_df[["Adj Close"]]
single_df.columns = ["SPY"]

In [4]:
data = pd.read_csv("sp_prices.csv", index_col=0)
data

,FLT,HLT,PKI,CAT,EOG,NOW,VRSK,PEG,ATVI,AJG,...,LOW,MTB,NIMC,CDW,SIVBP,UNP,PAYC,CTLT,HBI,ALLE
Date,,,,,,,,,,,,,,,,,,,,,
2014-01-02,118.379997,42.951488,39.589897,71.146545,73.821861,55.689999,63.953556,23.652208,17.043392,38.056103,...,43.074100,94.412491,NaN,21.583744,NaN,70.663208,NaN,NaN,13.897346,40.759880
2014-01-03,116.620003,43.246220,39.850994,71.106949,73.616066,55.180000,63.963367,23.727699,17.250895,38.064358,...,42.647194,94.535568,NaN,21.574512,NaN,70.553261,NaN,NaN,13.885354,41.049335
2014-01-06,116.110001,43.226559,40.315166,70.172798,73.374512,55.730000,62.509876,23.871132,17.052826,38.031361,...,42.046043,94.240158,NaN,21.925312,NaN,69.838646,NaN,NaN,13.817418,40.787888
2014-01-07,116.550003,43.226559,40.721310,70.402390,74.640511,57.779999,62.470589,23.893784,17.279192,39.045658,...,42.150578,94.757111,NaN,22.137642,NaN,70.456001,NaN,NaN,13.747482,40.965298
2014-01-08,117.800003,43.285515,41.291859,70.568634,74.609184,57.889999,62.225067,23.765446,17.298056,38.921955,...,42.298683,95.019699,NaN,22.137642,NaN,70.587112,NaN,NaN,13.621600,40.974640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-04,241.750000,147.440002,171.990005,203.589996,90.900002,701.729980,216.600006,63.680000,68.230003,160.779999,...,237.779999,154.169998,108.029999,185.000000,26.530001,237.199997,512.000000,129.039993,17.651583,131.080002
2021-11-05,244.759995,151.839996,168.839996,205.880005,95.120003,692.010010,214.589996,64.190002,67.830002,160.259995,...,235.539993,155.089996,108.260002,187.070007,26.559999,238.830002,504.399994,122.209999,17.840000,131.410004
2021-11-08,247.389999,151.169998,173.190002,214.250000,96.989998,692.280029,214.910004,62.169998,66.820000,160.910004,...,234.789993,156.589996,107.849998,185.320007,26.570000,239.449997,511.420013,124.000000,17.809999,132.020004
2021-11-09,244.080002,148.460007,174.550003,209.809998,97.110001,691.270020,216.289993,62.160000,67.099998,161.559998,...,233.910004,154.610001,107.849998,187.020004,26.510000,241.000000,507.329987,125.040001,18.070000,132.970001
2021-11-10,243.759995,146.529999,175.880005,206.669998,94.290001,670.909973,213.820007,62.720001,66.660004,161.190002,...,232.550003,156.389999,108.519997,188.800003,26.379999,241.539993,491.600006,123.660004,17.990000,132.630005